name: Initial commit workflow

on:
  push:
    branches:
      - '**' 
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: write
  contents: read
  issues: write

jobs:
  cpissues:
    name: "Initial commit only"
    runs-on: ubuntu-latest
    steps:       
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: "Raise semaphore or quit"
        run: |
          if $(gh workflow disable template.yml); then
            echo ::notice title=Workflow successfully disabled::This also works as a raised semaphore - parallel workflow runs will see it and cancel
          else
            echo "::warning title=Another job got here first::This room is crowded - I'm outta here!"
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel
              exit 1
          fi
          
      - name: "Copying issues over"
        run: .github/template/cpissues.sh
        
      - name: "List the issues copied"
        run: gh issue list -s all